kunstmaan_page_part:
    pageparts:
        header:
            name: "Header"
            context: "header"
            types:
                - { name: "PageBanner", class: "{{ namespace|replace({'\\': '\\\\'}) }}\\Entity\\PageParts\\PageBannerPagePart" }
