services:
    {{ bundle.name|lower }}.default_locale_listener:
        class: {{ bundle.namespace }}\EventListener\DefaultLocaleListener
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments: [%defaultlocale%]
{% if demosite %}
    {{ bundle.name|lower }}.admin_menu_adaptor:
        class: {{ bundle.namespace }}\Helper\Menu\AdminMenuAdaptor
        arguments: ["@security.context"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
{% endif %}