{{ bundle.getName() }}_{{ entity_class|lower }}page_admin_list:
    resource: @{{ bundle.getName() }}/Controller/{{ entity_class }}/{{ entity_class }}PageAdminListController.php
    type:     annotation
    prefix:   /admin/{{ entity_class|lower }}page/
    requirements:
         _locale: %requiredlocales%
