name: "Home page"
rows:
    - regions: 
        - { name: "main", span: 9 }
        - { name: "banners", span: 3 }
    - regions:
        - { name: "slider", span: 9 }
    - regions: 
        - { name: "footer", span: 12 }
template: "~~~BUNDLE~~~::Pages\\HomePage\\pagetemplate.html.twig"