name: "Home page"
rows:
    - regions:
        - { name: "slider", span: 12 }
    - regions:
        - { name: "left_column", span: 4 }
        - { name: "middle_column", span: 4 }
        - { name: "right_column", span: 4 }
template: "~~~BUNDLE~~~::Pages\\HomePage\\pagetemplate.html.twig"