kunstmaan_page_part:
    pagetemplates:
        {{ entity_class|lower }}overviewpage:
            name: "{{ entity_class }} overview page"
            rows: []
            template: "Pages\\{{ entity_class }}OverviewPage\\pagetemplate.html.twig"
