kunstmaan_page_part:
    pagetemplates:
      {{ entity_class|lower }}page:
            name: "{{ entity_class }} page"
            rows:
                - regions:
                    - { name: "{{ entity_class|lower }}main", span: 12 }
            template: "Pages\\{{ entity_class }}Page\\pagetemplate.html.twig"
